### ISSUE TITLE
 [Feature request] rgbgfx 8x16 sprite option

### ISSUE THREAD

**Issue by CharlesVanEeckhout** [gbdev/rgbds#1412] opened 2024-06-20 12:31 UTC
I will call this option --sixteen in this issue, but I don't like this name.
Much like the --columns option, this option will alter the order in which tiles are read. If both --columns and --sixteen are enabled at once, rgbgfx should ignore the --sixteen option.
The height of the image (or the height of the slice, if the --slice option is used) must be a multiple of 16 pixels.

To read all tiles, read all pairs of rows of tiles in the image/slice from top to bottom.
For a given pair of rows of tiles in the image/slice, the order in which the tiles must be read is the following:
0: The first tile in the top row of the pair of rows
1: The tile directly below tile 0
2: The tile directly to the right of tile 0
3: The tile directly below tile 2
4: The tile directly to the right of tile 2
5: The tile directly below tile 4
... and so on, until the right edge of the image/slice is reached.
![image](https://github.com/gbdev/rgbds/assets/99271432/065da233-f249-4888-90a2-52c1a76cc7a7)

The --sixteen option is compatible with the --reverse option.
The output tileset image will have its tiles placed in the order described above.
The output tileset image's height must be a multiple of 16.
Since the output tileset image from the reverse option has to be entirely filled with tiles (this is a description of existing behavior), it can be deduced that the number of tiles must be a multiple of 2.

This would be a useful option to have for tilesets of sprites using 8x16 sprite mode, since the image would be organized in a way that reflects how the tiles are used in-game.

**Comment by Rangi42** [comment] 2024-06-20 12:32
Duplicate of #1005.

**Closed by Rangi42** 2024-06-20 12:32 UTC

**Comment by ISSOtm** [comment] 2024-06-20 14:39
Yep, agreed, that'd be really useful. Do you mind re-posting that image on #1005? It'll be useful as a reference.

Thank you!
