### ISSUE TITLE
[Feature Request] Variable-size charmap entries; charmap changes mid-string

### ISSUE THREAD

**Issue by sfiera** [gbdev/rgbds#1408] opened 2024-06-14 01:51 UTC
# Background

I’m working with a ROM that uses an encoding along the following lines:
```
テ | ス | ト |    で    | す
C3 | BD | C4 | 0F C3 DE | BD
```
It’s essentially JIS X 201, extended with control characters to switch between katakana and hiragana—note how で is encoded with the same `$C3` as テ, preceded by a hiragana-mode byte and followed by a dakuten byte.

Currently I handle this by using half-width kana and inserting the control characters manually with some otherwise unmapped characters (`ﾃｽﾄ«ﾃﾞｽ`) but it’s a little awkward.

# Requests

1. Allow charmaps to map inputs to variable-length sequences.
2. Support mapping inputs to a change of charmap.

I’m imagining something like the following:

```
NEWCHARMAP Katakana, ASCII
CHARMAP "テ", $C3
CHARMAP "デ", $C3, $DE
CHARMAP "て", $0F, $C3, SETCHARMAP Hiragana
CHARMAP "で", $0F, $C3, $DE, SETCHARMAP Hiragana
```

In practice, I’d probably write a macro `KANACHARMAP "デ", "で", $C3, $DE` to set up mappings 4 at a time.

I think the first feature seems pretty reasonable. It would also address #97 and something similar was discussed there. I think I would be able to implement it, if the maintainers believe it’s worth doing. Personally, I think it would make sense to support 0-length mappings too, for use cases like “ignore whitespace” though there might be objections to the obvious syntax (`CHARMAP " "`).

The second feature doesn’t look hard to implement either. The main issues are first, if the complexity is worth it, and second, what the syntax would be. I think my suggestion above is a little ugly, and it’s the kind of thing that invites bikeshedding. I’d propose that changes to the charmap during the string last only until the end of that string.

I’ve put these into a single feature request since the background is the same, but I could split out the second request.

**Comment by Rangi42** [comment] 2024-06-14 05:07
Thanks for this proposal! The auto-switching behavior sounds similar to what was proposed in #265. At the time it was closed saying:

> Given the complexity of this, I'm not sure it's a good idea to implement it within RGBASM. Further, with the introduction of `CHARLEN` and `CHARSUB` (#787), and perhaps using #97, it should be possible to instead write a macro pack that processes shift states like described.

I'd still agree with that statement. That leaves multi-byte charmapping, which is already covered by #97 (it requests the feature, and discusses different ways to potentially do it).

That issue mentions [charmap_w.innc](https://github.com/SnDream/charmap_w.inc), a macro implementation of the feature (similar to how [rgbds-structs](https://github.com/ISSOtm/rgbds-structs) implements structs, or [list.asm](https://pastebin.com/Ucngn8Pt) implements lists/arrays). I could help get macros to do auto-switching as well (one idea might be to inspect the UTF-8 bytes with `STRSUB` and identify hiragana vs katakana ranges).

Anyway, closing this as a duplicate of those.

**Closed by Rangi42** 2024-06-14 05:07 UTC

**Comment by Rangi42** [comment] 2024-06-14 05:24
Noting that if we did implement this feature as described, then the example from #97 could work like this:

```asm
	newcharmap text
	charmap " ", $20
	charmap "!", $21
	charmap "0", $30
	charmap "A", $41
	charmap "a", $61
	; ...etc...
	; brace introduces formatting control characters
	charmap "{", setcharmap ctrl

	newcharmap ctrl
	; closing brace returns to emitting text characters
	charmap "}", setcharmap text
	; ignore whitespace and commas within format declarations
	; just writing `charmap " "` would look incomplete, so
	; disallow that syntax and do a "redundant" state switch
	charmap " ", setcharmap ctrl
	charmap ",", setcharmap ctrl
	; actual format specifiers
	charmap "black", $10
	charmap "regular", $14
	charmap "reset", $10, $14
	; ...etc...
```

**Comment by Rangi42** [comment] 2024-06-14 05:33
Despite taking the time to write that little example above, I have misgivings about a feature that would implicitly switch charmaps. It seems too prone to being confusing for the end-user (or even the assembler devs) about what invisible state we're actually in at any given point of assembly. For instance, let's say `"R"` is mapped to `$10` in the katakana charmap and `$20` in the hiragana one.

```asm
setcharmap katakana
db "テストR" ; so far so good, this is all katakana and ends in $10
db "テストですR" ; this ended in hiragana, so presumably ends in $20
db "R" ; are we still in the hiragana charmap? is this $10 or $20?
```

Or:
```asm
setcharmap katakana
if charlen("テストです") > 2
  db "R" ; did evaluating `charlen` put us in the hiragana charmap? is this $10 or $20?
  ; would it make a difference if we used `strlen` which doesn't "care" about charmappings?
  ; or if we did it in a `db` or a `def` or an `if`?
endc
```

**Comment by Rangi42** [comment] 2024-06-14 05:41
> Currently I handle this by using half-width kana and inserting the control characters manually with some otherwise unmapped characters (`ﾃｽﾄ«ﾃﾞｽ`) but it’s a little awkward.

Would it be less or more awkward to use a spelled-out explicit separator? Like:

```asm
setcharmap katakana
db "テス<hira>です<kata>ト"
```

**Comment by sfiera** [comment] 2024-06-14 07:22
I think changes during a string should persist only to the end of the string. There’s still some potential for confusion; the following are two different sequences:
```assembly
db "これはテストです" ; switch to katakana before テスト
db "これは", "テストです" ; テスト mistakenly becomes hiragana
```
I see that as being equal or lesser to the confusion from macros. A macro has the ability to persist charmap changes beyond the end of the macro, while this is more limited.

I’ve been thinking about the macro approach and I have some ideas for how I might do it.

> > Currently I handle this by using half-width kana and inserting the control characters manually with some otherwise unmapped characters (`ﾃｽﾄ«ﾃﾞｽ`) but it’s a little awkward.
> 
> Would it be less or more awkward to use a spelled-out explicit separator? Like:
> 
> ```assembly
> setcharmap katakana
> db "テス<hira>です<kata>ト"
> ```

Maybe a bit less? I think I settled on «» because the documentation wasn’t clear about what happens in case of ambiguity. I’ve now read the rgbasm source and it’s clear that it explicitly prefers longest-match.

**Comment by SnDream** [comment] 2024-06-14 12:57
Currently rgbds has a lot of text related functions that can do some complex implementations that earlier versions couldn't. While I think the functions mentioned in #97 need to be built in, we can get there with macros first though.

For the first request, I believe [charmap_w.inc](https://github.com/SnDream/charmap_w.inc) can be used as an alternative.
For the second request, I think it can be done with expansion and modification on charmap_w.inc, similar to the TX_KATAKANA/TX_HIRAGANA auto switch in [this asm](https://github.com/pret/poketcg2/blob/master/src/macros/text.asm) .

**Comment by sfiera** [comment] 2024-06-16 11:32
Here’s what I came up with:
https://github.com/sfiera/gbkasm/blob/8ad0afaee58dbd8dc8a1804f6eff8ddd1d1bc77f/charmap.inc#L236-L270
Since I have two specific use cases (kana mode switches and diacritics), I wrote it to specifically handle those cases.

It’s definitely nicer to read than it used to be; compare [old](https://github.com/sfiera/gbkasm/blob/aedb0/bank_000.inc#L1326-L1332) with [new](https://github.com/sfiera/gbkasm/blob/8ad0afaee58dbd8dc8a1804f6eff8ddd1d1bc77f/bank_000.inc#L1326-L1332). There’s still some awkwardness; I need explicit kana mode switches at times. Clearly the original authors didn’t have similar support for automatic switches.
