### ISSUE TITLE
Crash when converting image with alpha channel

### ISSUE THREAD

**Issue by Jummit** [gbdev/rgbds#1145] opened 2023-06-19 09:50 UTC
When converting this image with a palette `rgbgfx` crashes:

![ball](https://github.com/gbdev/rgbds/assets/28286961/6013fa55-f8db-4696-b07d-14c698f5c0e4)

> rgbgfx -c "#FFFFFF,#cfcfcf,#686868,#000000;" ball.png -o  ball.2bpp

> rgbgfx: /build/rgbds/src/rgbds/src/gfx/process.cpp:662: static uint16_t TileData::rowBitplanes(const Png::TilesVisitor::Tile&, const Palette&, uint32_t): Assertion `index < palette.size()' failed.

This doesn't happen when the image has no alpha values and when no palette is specified.

**Comment by ISSOtm** [comment] 2023-06-19 10:26
Thank you for reporting the issue!

I have had a similar bug report via IM, though @datguywitha3ds didn't have assertions enabled so it instead misbehaved a lot. (So there is at least another reproducer; I don't have it at hand, can Valentina attach it, please?)

I'm guessing the issue is that the presence of an alpha channel reduces the palette size to 3, but this is not taken into account when validating the palette spec. (Though I don't think Valen used `-c`, so the issue may lie deeper.)

**Comment by Rangi42** [comment] 2023-11-01 18:41
I can't reproduce this with current master:

```
$ file ball.png
ball.png: PNG image data, 8 x 8, 8-bit/color RGBA, non-interlaced

$ sha1sum ball.png
c44c1abbd6abbe10356e98021e93d9a81b0d2872  ball.png

$ ./rgbgfx -vvvvv -c "#FFFFFF,#cfcfcf,#686868,#000000;" ball.png -o /dev/null
rgbgfx v0.6.1-31-g32bc68d0
Options:
	Bit depth: 2bpp
	Maximum 8 palettes
	Palettes contain 4 colors
	Explicit palette spec
	[
		#ffffff, #cfcfcf, #686868, #000000,
	]
	Input image slice: 0x0 pixels starting at (0, 0)
	Base tile IDs: [0, 0]
	Maximum 65535 tiles in bank 0, 0 in bank 1
	Input image: ball.png
	Output tile data: /dev/null
Ready.
Using libpng 1.6.37
Reading tiles...
Opened input file
PNG header signature is OK
Input image: 8x8 pixels, 8bpp RGB + alpha, not interlaced
No embedded palette
Image colors: [ #000000ff, #00000000, ]
Image contains 1 proto-palette
[ $0000, ]
{ 6739, 35ad, 0000, }
Generating unoptimized tile data...
```

**Comment by ISSOtm** [comment] 2023-11-01 21:54
And if the image is indexed?

**Comment by Rangi42** [comment] 2023-11-02 00:23
Well, the original report had that ball.png which was non-indexed, but it also works with an indexed file:

![ball-indexed](https://github.com/gbdev/rgbds/assets/35663410/481f2fe8-6339-448c-9550-541f1b569a5f)

```
$ file ball-indexed.png 
ball-indexed.png: PNG image data, 8 x 8, 8-bit colormap, non-interlaced

$ sha1sum ball-indexed.png 
e838fa5b6f3d7f53659920ef257dce98f8bee771  ball-indexed.png

$ ./rgbgfx -vvvvv -c "#FFFFFF,#cfcfcf,#686868,#000000;" ball-indexed.png -o /dev/null
rgbgfx v0.6.1-32-g73e9aac1
Options:
	Bit depth: 2bpp
	Maximum 8 palettes
	Palettes contain 4 colors
	Explicit palette spec
	[
		#ffffff, #cfcfcf, #686868, #000000,
	]
	Input image slice: 0x0 pixels starting at (0, 0)
	Base tile IDs: [0, 0]
	Maximum 65535 tiles in bank 0, 0 in bank 1
	Input image: ball-indexed.png
	Output tile data: /dev/null
Ready.
Using libpng 1.6.37
Reading tiles...
Opened input file
PNG header signature is OK
Input image: 8x8 pixels, 8bpp palette, not interlaced
Embedded palette has 2 colors: [#00000000, #000000ff]
Image colors: [ #000000ff, #00000000, ]
Image contains 1 proto-palette
[ $0000, ]
{ 6739, 35ad, 0000, }
Generating unoptimized tile data...
```

**Comment by Rangi42** [comment] 2023-11-02 03:06
@Jummit Can you please build rgbds `master` and confirm if this crash still occurs on your particular system?

**Comment by Jummit** [comment] 2023-11-02 08:55
> @Jummit Can you please build rgbds `master` and confirm if this crash still occurs on your particular system?

I can't reproduce this, seems like it's fixed.

**Comment by ISSOtm** [comment] 2023-11-02 09:16
That's puzzling, as I don't remember fixing this specific bug. The only commit modifying RGBGFX since this report was cfe432e, so we should test if the crash was fixed by that commit, to be sure.

**Comment by Jummit** [comment] 2023-11-02 10:19
For reference, this is the image I tested:

![player-ship](https://github.com/gbdev/rgbds/assets/28286961/78b7ecc8-48f2-4107-a2ab-814ad6219e64)

And this is the command:

`rgbgfx -c "#FFFFFF,#cfcfcf,#686868,#000000;" -o player-ship.2bpp player-ship.png`

I bisected it down to this commit: 6b0cab32a67247be33fcfa8d509603fb52020920

**Comment by ISSOtm** [comment] 2023-11-02 11:23
That commit looks unrelated, so colour me skeptical. Further testing is preferable.

**Comment by Jummit** [comment] 2023-11-02 13:00
> That commit looks unrelated, so colour me skeptical. Further testing is preferable.

Maybe the segfault is unrelated, but I can confirm that the command crashes in cc27169e and not in 6b0cab32.

I can't reproduce the initial crash because I don't know the exact commit. For reference, it's one in version `0.6.1-1`, as that's where the arch package currently is.

**Comment by Jummit** [comment] 2023-11-02 13:30
Ok, I can still reproduce it in master with assertions enabled.

**Comment by Rangi42** [comment] 2023-11-02 15:42
Maybe I'm doing something wrong. In the `master` branch, I do `make debug`, which builds with*out* defining `NDEBUG`. Adding a test `assert(2 + 2 == 5)` fails as expected. But running `./rgbgfx -c "#FFFFFF,#cfcfcf,#686868,#000000," -o player-ship.2bpp player-ship.png` does not trigger any assertions.

**Comment by ISSOtm** [comment] 2023-11-02 15:49
Mind that `make develop` didn't enable assertions by default before https://github.com/gbdev/rgbds/commit/28737d5778f05bd554e595360c1f94d21328d15d

**Comment by Rangi42** [comment] 2023-11-04 16:58
Even this does not trigger for any of the test images here:
```diff
-			assert(index < palette.size()); // The color should be in the palette
+			if (!(index < palette.size())) {
+				fprintf(stderr, "index %d >= palette.size() %d!\n",
+					index, palette.size());
+				exit(1);
+			}
```

**Comment by Jummit** [comment] 2023-11-04 18:09
Ok, this is weird. I can't reproduce anymore. I also can't find the commit where the assertion triggered...

**Comment by ISSOtm** [comment] 2023-11-05 09:19
```
cfe432ea656f28a6ca50cfcdadb7c9d26bbc263c is the first bad commit
commit cfe432ea656f28a6ca50cfcdadb7c9d26bbc263c
Author: ISSOtm <eldredhabert0@gmail.com>
Date:   Sat Aug 26 23:23:28 2023 +0200

    Enforce that transparent colours take slot #0 in all palettes
```

This commit was intended to fix those issues, so yep we're good here.

**Closed by ISSOtm** 2023-11-05 09:19 UTC
Labels: bug, rgbgfx
