### ISSUE TITLE
[Feature Request] Use global symbols to define section addresses

### ISSUE THREAD

**Issue by VariantXYZ** [gbdev/rgbds#926] opened 2021-10-04 16:04 UTC
Currently, SECTION addresses must be defined during assembly time, which means addresses must be calculated within the same file or manually determined based on adjustments from other files. It would be helpful to be able to have the ability to use global symbols as the section address, and have them resolve at link time (rather than 'instead', probably 'in addition to'). 

A possible use-case, code that references an auto-generated table:
```
GetTileset::
  ld hl, TilesetInfoTable
.tileset_table
```

Auto-generated file:
```
; Auto-generated
; TilesetTable should always be in the same bank as GetTileset
SECTION "Tileset Info Table", ROMX[GetTileset.tileset_table], BANK[BANK(GetTileset.tileset_table)]
TilesetInfoTable::
  dw TilesetInfo1
  dw TilesetInfo2
  dw TilesetInfo3
  dw TilesetInfo4
  dw TilesetInfo5
...
```

Or maybe something like a generated jump-table. There's a lot of possibilities here.

The main benefit is from a project organization standpoint: being able to automate some of the math away without giving up the granular control of the layout in the binary.

Of course, this probably becomes non-trivial when the linker must now deal with things going out of bounds... but, well, figured I'd ask.

**Comment by Rangi42** [comment] 2021-10-04 18:26
Duplicate of #244.

(It's definitely non-trivial to add; the current linker algorithm for placing floating sections can't really handle a constraint like "put these two sections in the same bank, but I don't care which one".)

**Closed by Rangi42** 2021-10-04 18:26 UTC

**Comment by aaaaaa123456789** [comment] 2021-10-04 22:38
That's a perfect use case for `INCLUDE`, though.

**Comment by VariantXYZ** [comment] 2021-10-05 00:23
Doh. You're right, that was a terrible example.

**Comment by VariantXYZ** [comment] 2021-10-05 00:33
I was trying to take my use-case and translate it more generically in a hurry, but lost some key context...

The situation I ran into was simply that we had some files/functions that only exist when certain flags are enabled (versions/features), and I wanted to make sure that any other routines that may have shared a bank with those functions were laid out without swathes of empty space that could be used for feature-specific resources if we needed them. 

Thinking on it more, ```INCLUDE``` might be the better solution there too. Egg on my face, thanks for the advice.
