### ISSUE TITLE
"See also" links on man pages are broken

### ISSUE THREAD

**Issue by tobiasvl** [gbdev/rgbds#1133] opened 2023-03-04 11:21 UTC
The links to the other man pages under the "SEE ALSO" heading are broken. They should link one directory above in the hierarchy.

Example: https://rgbds.gbdev.io/docs/v0.6.1/rgbasm.5/#SEE_ALSO

**Comment by ISSOtm** [comment] 2023-03-04 11:47
The problem is that the URLs used to be served *without* a trailing slash, and then the relative links worked correctly. Something changed, and now trailing slashes are enforced by GitHub Pages; two possible fixes are to either add a `../`, or to use the full path from the root.

Thoughts on which one is preferable?

**Comment by Rangi42** [comment] 2023-10-31 20:03
Full paths would work whether or not GitHub appends a trailing slash.

**Comment by ISSOtm** [comment] 2023-10-31 22:55
They however require modifying the generated HTML, which is its own pile of problems...

**Comment by Rangi42** [comment] 2023-11-06 23:19
The man pages themselves are fine; the fix for this will be some change to rgbds-www. So https://github.com/gbdev/rgbds-www/issues/45 is the GitHub issue for resolving it.

**Closed by Rangi42** 2023-11-06 23:19 UTC
Labels: docs
