### ISSUE TITLE
JR n16 & JR cc n16 Ambigious name

### ISSUE THREAD

**Issue by jevon-23** [gbdev/rgbds#1124] opened 2023-01-06 00:15 UTC
https://rgbds.gbdev.io/docs/v0.6.0/gbz80.7/#JR_n16

Should JR n16 be JR n8?

It reads in the next byte after the instruction opcode, and uses it as the address to jump to. The byte is only an 8-bit range though, so it makes more sense for me for this to be JR n8.

Also I believe the opcode table has it written as JR n8: https://gbdev.io/gb-opcodes/optables/

**Comment by eievui5** [comment] 2023-01-06 00:16
These docs describe the syntax, not the underlying representation, and RGBASM expects a 16-bit destination rather than an 8-bit offset

**Comment by Rangi42** [comment] 2023-01-06 03:19
Duplicate of #1020.

**Closed by Rangi42** 2023-01-06 03:19 UTC

**Comment by jevon-23** [comment] 2023-01-06 03:25
Ahh makes sense, thanks for the clarification!

**Comment by benjschro** [comment] 2023-01-27 19:02
I'm not sure if anyone watches closed issues, but I will open a new issue if this doesn't have visibility.

I want to mention that I just stumbled on this too. Can I recommend that if the assembler recognizes a 16 bit operand to this instruction, it should instead be called a pseudo-instruction? Without being precise, this could cause problems for someone who is more familiar with the actual CPU's instruction set.

**Comment by eievui5** [comment] 2023-01-27 19:06
That would be misleading because it’d imply we provide a non-pseudo version. If anything we could improve the wording so that people stop misreading it

**Comment by benjschro** [comment] 2023-01-27 19:40
Yeah, that is a good point. Since this is already implemented the way it is, I can't think of a practical way of supporting jump variants without breaking backwards compatibility. My preference would have been that if the assembler can decide what happens under the hood, then there should just have a generic "J" pseudo-instruction that then gets turned into a JR or JP as appropriate. As it reads now, the descriptions for JP/JR CC, n16 don't really tell the developer which one should be used. The non-conditional JR n16 has a good note though.

The specific bit that caught me out is that the mnemonic for JR is "Jump Relative", but an absolute address is being provided. Maybe if there was clarification that just removed the word relative, but indicated the -128/+127 range constraint, that should be enough.

**Comment by eievui5** [comment] 2023-01-27 19:44
a `j` isn't possible because the size of the code would change at link time and then there's no way for the linker to figure out where the `j` should end up.

**Comment by benjschro** [comment] 2023-01-27 20:02
Hmm, yeah.. that would be it difficult to implement.

Either way, I think what's done is done. I'll toy around with raising a pull request for a documentation update after I've gotten through more of it to see if there are other similar situations.

**Comment by ISSOtm** [comment] 2023-01-28 20:10
> I want to mention that I just stumbled on this too. Can I recommend that if the assembler recognizes a 16 bit operand to this instruction, it should instead be called a pseudo-instruction? Without being precise, this could cause problems for someone who is more familiar with the actual CPU's instruction set.

The instruction is exactly as described: it jumps *to* a certain address, which is simply *encoded* in a different way.

This is further compounded by everyone wanting to write the target address, and not having to compute the offset themselves—isn't that what we use an assembler for?—and by every disassembler in existence (even those in e.g. emulators) also displaying the target address. It's not just about backwards compat, it's about the behaviour everyone desires.

What may be misleading is the `n16` notation, which could have been e.g. `addr`, but then we'd get other nitpicks that "well actually you can write any number even if it's not a label"; so I think it's better to keep using the same `n16` that's introduced at the top of the list for immediate 16-bit operands.

However, changing the mnemonic to remove the "relative" *would* absolutely break compat with basically every single codebase out there, not to mention be yet another departure from Z80 syntax, so I really don't want to do this without a compelling reason to.

**Comment by aaaaaa123456789** [comment] 2023-01-29 13:12
> but then we'd get other nitpicks that "well actually you can write any number even if it's not a label"

Writing "address" is fine; writing "label" is, as you said, problematic.
