### ISSUE TITLE
Warn for all LD that can be optimized to LDH, not only first

### ISSUE THREAD

**Issue by pinobatch** [gbdev/rgbds#1114] opened 2022-12-11 23:28 UTC
By default, RGBASM optimizes `ld` to `ldh` where possible. I'm told the default will soon change to no optimization, in the interest of what you write is what you get. If the user specifies neither optimization nor no optimization on the command line, RGBASM emits a warning (from [parser.y](https://github.com/gbdev/rgbds/blob/01f1703dfb64b6a859e04e077249881c3857dd06/src/asm/parser.y#L1949-L1952)) when optimizing. However, RGBASM suppresses this warning (`warnOnLdOpt = false;`) after the first occurrence in each translation unit, making it more tedious for me to go in and fix them all.

So here's the behavior that I'd like to see going forward (names are flexible):

1. `-L`, `-fno-ldh`, `--preserve-ld` (default): no optimization
2. `-l`, `-fldh`, `--auto-ldh`: optimization
3. `-Wldh` to trigger this warning without suppressing it after the first instance

**Comment by Rangi42** [comment] 2022-12-11 23:36
Issue #986 is regarding the gradual deprecation and removal of `ld`-to-`ldh` auto-optimization (and the similar `nop`-after-`halt` auto-insertion). Previously they were the default behavior, with `-L` and `-h` flags to disable that behavior. Currently the `-l` and `-H` flags exist to explicitly enable them, and the first usage of `ld` or `halt` triggers a warning if you didn't explicitly opt into one or the other. Eventually the no-behavior will be the default, with opting into the auto-behavior warned as deprecated, then removed.

Separately, issue #1017 is regarding rgblink warnings for possible optimizations (but not doing them automatically). Those could be allowed for all instances or only the first, and could exist for many such patterns (`ld` when it could be `ldh`, but also `jp` when it could be `jr`, and maybe others like tail `call`+ret`, redundant operations, etc). This would have to be a link-time behavior since too much might be unknown at asm time.

I think this issue can be closed as a duplicate of those.

**Closed** 2022-12-11 23:42 UTC
